name: Deploy EC2 Instance - QA

on:
  push:
    branches:
      - qa   # ✅ Trigger only on qa branch
    paths:
      - 'infrastructure/ec2/**'
      - '.github/workflows/deploy-ec2-qa.yaml'

env:
  TF_VERSION: 1.4.0
  AWS_REGION: ap-south-1

jobs:
  terraform:
    name: Terraform Init, Format, Validate, Plan, Apply for EC2 (QA)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials for QA
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.QA_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.QA_AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          export TF_LOG=DEBUG
          terraform -chdir=infrastructure/ec2 init

      - name: Terraform fmt
        run: terraform fmt
        working-directory: infrastructure/ec2

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var-file=qa.tfvars
        working-directory: infrastructure/ec2

      - name: Terraform Show Plan
        run: |
          export TF_LOG=DEBUG
          terraform show tfplan
        working-directory: infrastructure/ec2

      - name: Terraform Apply
        if: github.ref == 'refs/heads/qa'
        run: terraform -chdir=infrastructure/ec2 apply -auto-approve -var-file=qa.tfvars
