name: Terraform CI - Dev

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'infrastructure/s3/**'
      - '.github/workflows/**'

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 1.5.0
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=infrastructure/s3 init

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: infrastructure/s3

      - name: Terraform Validate
        run: terraform validate
        working-directory: infrastructure/s3

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars
        working-directory: infrastructure/s3
